### PR TITLE
Fix preprocessor error on non-RHEL kernels >= 7.0

### PR DESCRIPTION
**Pull request by sergiobaiao**
## Problem

Building on non-RHEL kernels >= 7.0 (e.g. Ubuntu mainline) fails with:

```
gasket_interrupt.c:162:88: error: missing binary operator before token '('
    (defined RHEL_RELEASE_CODE && RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(9, 5))

gasket_core.c:1849:76: error: missing binary operator before token '('
    (defined RHEL_RELEASE_CODE && RHEL_RELEASE_CODE >= RHEL_RELEASE_VERSION(9, 4))
```

`RHEL_RELEASE_VERSION` is a function-like macro defined only on RHEL kernels. When used in a compound `#if` expression on non-RHEL kernels, GCC expands **all** macros before evaluating logical operators — there is no short-circuit at expansion time. The undefined `RHEL_RELEASE_VERSION` expands to `0`, and the trailing `(9, x)` argument list then produces the "missing binary operator" syntax error, even though `defined RHEL_RELEASE_CODE` is false.

## Fix

Restructure both affected guards into nested `#ifdef` blocks so `RHEL_RELEASE_VERSION()` is only reached by the preprocessor on kernels where it is defined:

- **`gasket_interrupt.c`**: `eventfd_signal()` arity guard (`>= 6.8.0` / RHEL 9.5 backport)
- **`gasket_core.c`**: `class_create()` arity guard (`>= 6.4.0` / RHEL 9.4 backport)

The logic is equivalent to the original intent — RHEL backport paths are preserved — but the preprocessor no longer encounters `RHEL_RELEASE_VERSION()` on kernels where it is undefined.

## Test

Verified build and `dpkg -i` install on Ubuntu kernel `7.0.0-15-generic`. Both `gasket.ko` and `apex.ko` compile, sign, and install via DKMS successfully.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by bennydiamond** [comment]
Confirmed working on Promox 9 with kernel 7.0.6-2-pve

**Comment by sergiobaiao** [comment]
please merge this, and also put the commands to build the packages back on the README:

debuild -us -uc -tc -b (for debian/ubuntu at least)
