### ISSUE TITLE
Kernel 6.8 dkms issue

### ISSUE THREAD

**Issue by csreynolds** [KyleGospo/gasket-dkms#9]
Fails to build on any 6.8 kernel that I've tried.

6.7 works fine.
```
[root@fedorabox ~]$ dkms install gasket/0.0.git.252.c41789f9 -k 6.8.5-201.fc39.x86_64
Sign command: /lib/modules/6.8.5-201.fc39.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
Building module(s)...(bad exit status: 2)
Failed command:
make -j40 KERNELRELEASE=6.8.5-201.fc39.x86_64 KERNEL_SOURCE_DIR=/lib/modules/6.8.5-201.fc39.x86_64/build
Error! Bad return status for module build on kernel: 6.8.5-201.fc39.x86_64 (x86_64)
Consult /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/make.log for more information.
```

/var/lib/dkms/gasket/0.0.git.252.c41789f9/build/make.log:
```
DKMS make.log for gasket-0.0.git.252.c41789f9 for kernel 6.8.5-201.fc39.x86_64 (x86_64)
Sun Apr 14 10:18:04 AM EDT 2024
make -C "/lib/modules/6.8.5-201.fc39.x86_64/build" M="/var/lib/dkms/gasket/0.0.git.252.c41789f9/build" modules
make[1]: Entering directory '/usr/src/kernels/6.8.5-201.fc39.x86_64'
  CC [M]  /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_page_table.o
  CC [M]  /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_sysfs.o
  CC [M]  /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/apex_driver.o
/var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
/var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_interrupt.c:161:17: error: too many arguments to function ‘eventfd_signal’
  161 |                 eventfd_signal(ctx, 1);
      |                 ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_interrupt.h:11,
                 from /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_interrupt.c:4:
./include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/gasket/0.0.git.252.c41789f9/build/gasket_interrupt.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/kernels/6.8.5-201.fc39.x86_64/Makefile:1939: /var/lib/dkms/gasket/0.0.git.252.c41789f9/build] Error 2
make[1]: *** [Makefile:252: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.8.5-201.fc39.x86_64'
make: *** [Makefile:15: all] Error 2

```

**Comment by csreynolds** [comment]
I should have gone a few more clicks into the internet.

Looks like this is it: https://github.com/google/gasket-driver/pull/26

**Comment by bbccdd** [comment]
Indeed, it works fine now. Great, thanks!

You helped out quite a few as you can see here: https://forum.proxmox.com/threads/update-error-with-coral-tpu-drivers.136888/post-657068

**Comment by csreynolds** [comment]
Looks like #10 fixed it!
