### ISSUE TITLE
Kernel 6.14.x (Ubuntu 24.04) fails to install gasket_dkms.deb build from sources

### ISSUE THREAD

**Issue by x00e** [KyleGospo/gasket-dkms#20]
````
❯ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.2 LTS"
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

❯ uname -r
6.14.0-24-generic
````

Following instructions to clone repo & build .deb file, I do a get .deb file, but this package fails to successfully install:

````
❯ sudo dpkg -i gasket-dkms_1.0-18_all.deb
(Reading database ... 182056 files and directories currently installed.)
Preparing to unpack gasket-dkms_1.0-18_all.deb ...
Deleting module gasket-1.0 completely from the DKMS tree.
Unpacking gasket-dkms (1.0-18) over (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
locale: Cannot set LC_ALL to default locale: No such file or directory
Loading new gasket-1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.14.0-24-generic
Building initial module for 6.14.0-24-generic
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/gasket-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.14.0-24-generic (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--install):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms

❯ cat  /var/lib/dkms/gasket/1.0/build/make.log
DKMS make.log for gasket-1.0 for kernel 6.14.0-24-generic (x86_64)
Fri Jul 18 11:38:24 AM UTC 2025
make: Entering directory '/usr/src/linux-headers-6.14.0-24-generic'
make[1]: Entering directory '/var/lib/dkms/gasket/1.0/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  gasket_core.o
  CC [M]  gasket_ioctl.o
  CC [M]  gasket_interrupt.o
  CC [M]  gasket_page_table.o
gasket_core.c:1376:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
 1376 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
In file included from /usr/src/linux-headers-6.14.0-24-generic/include/linux/module.h:22,
                 from /usr/src/linux-headers-6.14.0-24-generic/include/linux/device/driver.h:21,
                 from /usr/src/linux-headers-6.14.0-24-generic/include/linux/device.h:32,
                 from /usr/src/linux-headers-6.14.0-24-generic/include/linux/pci.h:37,
                 from gasket_page_table.h:15,
                 from gasket_page_table.c:42:
gasket_page_table.c:57:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
/usr/src/linux-headers-6.14.0-24-generic/include/linux/moduleparam.h:26:61: note: in definition of macro ‘__MODULE_INFO’
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/usr/src/linux-headers-6.14.0-24-generic/include/linux/module.h:301:33: note: in expansion of macro ‘MODULE_INFO’
  301 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
gasket_page_table.c:57:1: note: in expansion of macro ‘MODULE_IMPORT_NS’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.14.0-24-generic/scripts/Makefile.build:207: gasket_core.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [/usr/src/linux-headers-6.14.0-24-generic/scripts/Makefile.build:207: gasket_page_table.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.14.0-24-generic/Makefile:2002: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.14.0-24-generic/Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/gasket/1.0/build'
make: *** [Makefile:251: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.14.0-24-generic'
````

**Comment by vasyna** [comment]
https://github.com/google/gasket-driver/issues/52#issue-3325526554
https://github.com/sethyx/gasket-driver
may be you need remove 57-59 and 61 strings from gasket_page_table.c in sethyx repo

**Comment by Bodengriller** [comment]
have a look at this PR: [https://github.com/google/gasket-driver/pull/50](https://github.com/google/gasket-driver/pull/50) 
@feranick fixed that in his fork

**Comment by feranick** [comment]
Here's the link to the deb from my fork.  

https://github.com/feranick/gasket-driver/releases/tag/1.0-18.4

**Comment by yousaf465** [comment]
does @feranick solution work on trixie debian too? I am trying to build for 6.14 on Proxmox 9.0.6

**Comment by vasyna** [comment]
> does [@feranick](https://github.com/feranick) solution work on trixie debian too? I am trying to build for 6.14 on Proxmox 9.0.6

https://github.com/markfrancisonly/frigate_debian_scripts/blob/master/install_coral_tpu.sh
if use proxmox need change kernel naming

**Comment by Popoff-fr** [comment]
@vasyna  I used your script on proxmox 9.0.9 but it returns :
```
Error: Unable to locate package linux-headers-6.14.11-2-pve
Error: Couldn't find any package by glob 'linux-headers-6.14.11-2-pve'
```
For some reason, I have multiple kernels installed.

<img width="1045" height="43" alt="Image" src="https://github.com/user-attachments/assets/afaad728-24c4-4cdd-a8af-41a179f1cdbb" />

I don't know if that's the explanation.....

**Comment by feranick** [comment]
You can't compile the driver without the headers. This is unrelated to Trixie (which uses 6.12). and certainly an issue that concerns how proxmox deals with kernels. As you can't understand, I can't provide support for highly customized builds. 

This issue would be better addressed by whoever maintains proxmox.

**Comment by feranick** [comment]
> does [@feranick](https://github.com/feranick) solution work on trixie debian too? I am trying to build for 6.14 on Proxmox 9.0.6

It should. Packages for Trixie are available here:

https://github.com/feranick/libedgetpu/releases/tag/16.0TF2.17.1-1

(I'd note, again, that this package should work for pure Trixie, i.e. with the default kernel, and not with other alternative configurations using customized kernels).

**Comment by vasyna** [comment]
> [@vasyna](https://github.com/vasyna) I used your script on proxmox 9.0.9 but it returns :
> 
> ```
> Error: Unable to locate package linux-headers-6.14.11-2-pve
> Error: Couldn't find any package by glob 'linux-headers-6.14.11-2-pve'
> ```
> 
> For some reason, I have multiple kernels installed.
> 
> <img alt="Image" width="1045" height="43" src="https://private-user-images.githubusercontent.com/126980530/489717994-afaad728-24c4-4cdd-a8af-41a179f1cdbb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc5OTk5NTgsIm5iZiI6MTc1Nzk5OTY1OCwicGF0aCI6Ii8xMjY5ODA1MzAvNDg5NzE3OTk0LWFmYWFkNzI4LTI0YzQtNGNkZC1hOGFmLTQxYTE3OWYxY2RiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxNlQwNTE0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGI3YjMxMzc4NTFjYzE2NWU1MWNjZWY4MzkzMWIxZWVhMTkwMDk2NzZiYjhlN2FkZTkyM2IyMjk4YWM4ZWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0S8laDUQdqpboFS_U2xHGz8MvEqh6VMCJmrfXbV8zrk">
> I don't know if that's the explanation.....

change kernel naming in script

**Comment by Popoff-fr** [comment]
So there was definitely a problem with the header.
The header wasn't the same version as the kernel.
I don't know why.
I used : 
`sudo apt install linux-headers-$(uname -r)`
This set the header to the same version as the kernel.
Then I restarted the driver installation (@feranick version) and after a reboot it was installed.
Thank you very much @feranick for taking the time to answer me, you put me on the right track.
